FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN echo "MIDTRANS_CLIENT_KEY_SANDBOX=${MIDTRANS_CLIENT_KEY_SANDBOX}" >> .env
RUN echo "MIDTRANS_SERVER_KEY_SANDBOX=${MIDTRANS_SERVER_KEY_SANDBOX}" >> .env
RUN echo "NEXT_PUBLIC_MIDTRANS_CLIENT_KEY_SANDBOX=${MIDTRANS_CLIENT_KEY_SANDBOX}" >> .env

RUN npm run build && npm run build:cron

EXPOSE 3000

ENV NODE_ENV="production"
ENV PORT=3000

CMD ["npm", "start"]