name: Healio-AI CI/CD Pipeline (MongoDB to Server & Web to Vercel)

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  deploy-mongodb:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref_name == 'master' || github.ref_name == 'dev')
    steps:
      - name: Deploy MongoDB to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            set -e
            trap 'echo "An error occurred during MongoDB deployment. Exiting..." && exit 1' ERR

            SCRIPT_BRANCH_NAME="${{ github.ref_name }}"
            REPO_URL="https://github.com/elginbrian/Healio.ai.git" # Pastikan ini URL repo Anda
            TARGET_DIR="healio-ai-app-mongo" # Nama direktori bisa disesuaikan

            echo "Deploying MongoDB for branch: $SCRIPT_BRANCH_NAME from $REPO_URL"

            if [ -z "$SCRIPT_BRANCH_NAME" ]; then
              echo "Critical Error: SCRIPT_BRANCH_NAME is empty."
              exit 1
            fi

            if [ "$SCRIPT_BRANCH_NAME" = "master" ]; then
              MONGO_HOST_PORT_VALUE="27017"
              MONGO_INITDB_DATABASE_VALUE="healio_db_prod"
            elif [ "$SCRIPT_BRANCH_NAME" = "dev" ]; then
              MONGO_HOST_PORT_VALUE="27018"
              MONGO_INITDB_DATABASE_VALUE="healio_db_dev"
            else
              echo "Error: Branch '$SCRIPT_BRANCH_NAME' is not 'master' or 'dev'. MongoDB deployment skipped."
              exit 1
            fi

            echo "Preparing deployment directory: $TARGET_DIR"
            if [ -d "$TARGET_DIR" ]; then
              echo "Found existing directory: $TARGET_DIR. Will update content."
              cd "$TARGET_DIR"
              echo "Pulling latest changes for branch $SCRIPT_BRANCH_NAME..."
              # Hapus perubahan lokal jika ada, lalu pull. Atau hapus dan clone ulang.
              # Untuk kesederhanaan dan kebersihan, hapus dan clone ulang lebih aman.
              cd .. # Kembali ke parent dari TARGET_DIR
              rm -rf "$TARGET_DIR"
              echo "Cloning repository $REPO_URL (branch $SCRIPT_BRANCH_NAME) into $TARGET_DIR..."
              git clone --branch $SCRIPT_BRANCH_NAME $REPO_URL $TARGET_DIR
            else
              echo "Cloning repository $REPO_URL (branch $SCRIPT_BRANCH_NAME) into $TARGET_DIR..."
              git clone --branch $SCRIPT_BRANCH_NAME $REPO_URL $TARGET_DIR
            fi

            cd "$TARGET_DIR"
            echo "Successfully changed directory to $TARGET_DIR"
            echo "Current directory content:"
            ls -la

            if [ ! -f "./docker-compose.yml" ]; then
                echo "Error: docker-compose.yml not found in the cloned repository at $(pwd)/docker-compose.yml"
                exit 1
            fi
            echo "Using docker-compose.yml found in cloned repository."

            echo "Creating .env file for MongoDB in $TARGET_DIR/.env ..."
            # Menggunakan sintaks yang benar untuk variabel shell di dalam heredoc .env
            # Variabel ini akan dibaca oleh docker-compose
            cat > .env <<-EOF
            MONGO_HOST_PORT=${MONGO_HOST_PORT_VALUE}
            MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE_VALUE}
            # Jika Anda menggunakan autentikasi MongoDB, tambahkan:
            # MONGO_INITDB_ROOT_USERNAME=${{ secrets.MONGO_USER }}
            # MONGO_INITDB_ROOT_PASSWORD=${{ secrets.MONGO_PASSWORD }}
            EOF

            echo "Environment variables for MongoDB docker-compose set."

            echo "Stopping and removing existing MongoDB services defined in docker-compose.yml (if any)..."
            docker-compose down --remove-orphans || true

            echo "Pulling latest MongoDB image (if needed)..."
            docker-compose pull mongodb || true

            echo "Starting MongoDB service with docker-compose..."
            # --force-recreate mungkin tidak lagi sepenuhnya diperlukan setelah 'down',
            # tapi tidak berbahaya untuk disertakan.
            docker-compose up -d --force-recreate mongodb

            echo "MongoDB deployment for branch $SCRIPT_BRANCH_NAME completed successfully."
